<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql
SELECT * FROM sales
LIMIT 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00


In [ ]:
%%sql
SELECT * FROM customer
LIMIT 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71
3,120,6,1983-07-23,2033-08-09,Australia,male,Mr.,Jamie,H,Hetherington,...,7256,AU,Australia,1946-12-11,74,Dental laboratory technician,Showbiz Pizza Place,2006 Dodge Durango,-39.77,144.02
4,180,7,1987-11-26,2026-10-14,Australia,male,Mr.,Gabriel,P,Bosanquet,...,3505,AU,Australia,1955-04-24,65,Administrative support specialist,Dubrow's Cafeteria,1995 Morgan Plus 4,-34.13,142.14


In [ ]:
%%sql
SELECT
  DATE_TRUNC('month', orderdate)::date AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM sales
GROUP BY
  order_month
LIMIT 10



Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,order_month,net_revenue,total_unique_customers
0,2015-01-01,384092.66,200
1,2015-02-01,706374.12,291
2,2015-03-01,332961.59,139
3,2015-04-01,160767.00,78
4,2015-05-01,548632.63,236
5,2015-06-01,748563.97,238
6,2015-07-01,635376.13,227
7,2015-08-01,718538.62,235
8,2015-09-01,696805.68,277
9,2015-10-01,824891.22,304


In [ ]:
%%sql
SELECT
  orderdate,
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month
FROM sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_month
0,2015-01-01,2015-01
1,2015-01-01,2015-01
2,2015-01-01,2015-01
3,2015-01-01,2015-01
4,2015-01-01,2015-01
5,2015-01-01,2015-01
6,2015-01-01,2015-01
7,2015-01-01,2015-01
8,2015-01-01,2015-01
9,2015-01-01,2015-01


In [ ]:
%%sql
SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(MONTH FROM orderdate) AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
GROUP BY
  order_year,
  order_month
ORDER BY
  order_year,
  order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

,order_year,order_month,net_revenue
0,2015,1,384092.66
1,2015,2,706374.12
2,2015,3,332961.59
3,2015,4,160767.00
4,2015,5,548632.63
...,...,...,...
107,2023,12,2928550.93
108,2024,1,2677498.55
109,2024,2,3542322.55
110,2024,3,1692854.89


In [ ]:
%%sql
SELECT
  CURRENT_DATE,
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_price
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  --EXTRACT(YEAR FROM orderdate) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5
  orderdate >= CURRENT_DATE - INTERVAL '5 years'
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

7974 rows affected.

,current_date,orderdate,categoryname,net_price
0,2026-06-10,2021-06-10,Audio,474.58
1,2026-06-10,2021-06-10,Cameras and camcorders,10916.53
2,2026-06-10,2021-06-10,Cell phones,16015.71
3,2026-06-10,2021-06-10,Computers,80481.52
4,2026-06-10,2021-06-10,Games and Toys,304.85
...,...,...,...,...
7969,2026-06-10,2024-04-20,Computers,58353.68
7970,2026-06-10,2024-04-20,Games and Toys,1744.30
7971,2026-06-10,2024-04-20,Home Appliances,1562.04
7972,2026-06-10,2024-04-20,"Music, Movies and Audio Books",4949.43


In [ ]:
%%sql
SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  ROUND(AVG(EXTRACT(DAY FROM AGE(deliverydate, orderdate))), 2) AS avg_processing_time,
  CAST(SUM(netprice * quantity * exchangerate) AS INTEGER) AS net_revenue
FROM sales
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '6 years'
GROUP BY
  order_year
ORDER BY
  order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,order_year,avg_processing_time,net_revenue
0,2020,0.97,3252353
1,2021,1.36,21357977
2,2022,1.62,44864557
3,2023,1.75,33108566
4,2024,1.67,8396527


WINDOW FUNCTION:


1. Syntax: OVER() & PARTITION BY, EXTRACT()
2. Aggregation: SUM(), COUNT(), AVERAGE()
3. Ranking: RANK(), DENSE_RANK()
4. Lag&Lead: FIRST_VALUE(), LAG, LEAD()
5. Frame Clause: N PRECEDING, N FOLLOWING



In [ ]:
%%sql
SELECT
  customerkey,
  orderkey,
  linenumber,
  netprice * quantity * exchangerate AS net_revenue,
  AVG(netprice * quantity * exchangerate) OVER (
    PARTITION BY customerkey
  ) AS avg_net_revenue_this_customer
FROM sales
ORDER BY
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_this_customer
0,15,2259001,0,2217.41,2217.41
1,180,3162018,1,1913.55,836.74
2,180,3162018,0,71.36,836.74
3,180,1305016,0,525.31,836.74
4,185,1613010,0,1395.52,1395.52
5,243,505008,0,287.67,287.67
6,387,1451007,1,619.77,517.32
7,387,1451007,0,1608.10,517.32
8,387,1451007,2,97.05,517.32
9,387,1451007,3,45.62,517.32


In [ ]:
%%sql
SELECT
  customerkey,
  orderkey,
  orderdate,
  linenumber,
  netprice * quantity * exchangerate AS net_revenue,
  ROW_NUMBER() OVER (
    PARTITION BY customerkey
    ORDER BY netprice * quantity * exchangerate DESC
  ) AS order_rank,
  SUM(netprice * quantity * exchangerate) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate
  ) AS customer_running_total,
  SUM(netprice * quantity * exchangerate) OVER (
    PARTITION BY customerkey
  ) AS customer_revenue,
  (netprice * quantity * exchangerate) / SUM(netprice * quantity * exchangerate) OVER (PARTITION BY customerkey) * 100 AS pct_customer_revenue
FROM sales
ORDER BY
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,orderdate,linenumber,net_revenue,order_rank,customer_running_total,customer_revenue,pct_customer_revenue
0,15,2259001,2021-03-08,0,2217.41,1,2217.41,2217.41,100.00
1,180,3162018,2023-08-28,1,1913.55,1,2510.22,2510.22,76.23
2,180,1305016,2018-07-28,0,525.31,2,525.31,2510.22,20.93
3,180,3162018,2023-08-28,0,71.36,3,2510.22,2510.22,2.84
4,185,1613010,2019-06-01,0,1395.52,1,1395.52,1395.52,100.00
5,243,505008,2016-05-19,0,287.67,1,287.67,287.67,100.00
6,387,1451007,2018-12-21,0,1608.10,1,2370.54,4655.84,34.54
7,387,2495044,2021-10-30,0,1265.56,2,3636.10,4655.84,27.18
8,387,1451007,2018-12-21,1,619.77,3,2370.54,4655.84,13.31
9,387,3242015,2023-11-16,3,446.44,4,4655.84,4655.84,9.59


In [ ]:
%%sql
SELECT *,
  100 * net_revenue / daily_net_revenue AS pct_daily_net_revenue
FROM (
  SELECT
    orderdate,
    orderkey * 10 + linenumber AS order_line_number,
    netprice * quantity * exchangerate AS net_revenue,
    SUM(netprice * quantity * exchangerate) OVER (
      PARTITION BY orderdate
    ) AS daily_net_revenue
  FROM sales
) AS revenue_by_day
ORDER BY
  orderdate,
  pct_daily_net_revenue DESC

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_net_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
...,...,...,...,...,...
199868,2024-04-20,33980141,12.00,96879.43,0.01
199869,2024-04-20,33980074,9.29,96879.43,0.01
199870,2024-04-20,33980080,8.35,96879.43,0.01
199871,2024-04-20,33980142,8.34,96879.43,0.01


In [ ]:
%%sql
WITH yearly_cohort AS (
  SELECT DISTINCT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
  FROM sales
)
SELECT
  y.cohort_year,
  EXTRACT(YEAR FROM s.orderdate) AS purchase_year,
  SUM(s.netprice * s.quantity * s.exchangerate) AS net_revenue
FROM sales s
LEFT JOIN yearly_cohort y ON s.customerkey = y.customerkey
GROUP BY
  y.cohort_year,
  purchase_year


Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

,cohort_year,purchase_year,net_revenue
0,2015,2015,7370979.48
1,2015,2016,392623.48
2,2015,2017,479841.31
3,2015,2018,1069850.87
4,2015,2019,1235991.48
5,2015,2020,386489.60
6,2015,2021,872845.99
7,2015,2022,1569787.72
8,2015,2023,1157633.91
9,2015,2024,356186.62


In [ ]:
%%sql
-- Cải tiến
WITH yearly_cohort AS (
  SELECT
    EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year,
    (netprice * quantity * exchangerate) AS line_revenue
  FROM sales
)
SELECT
  cohort_year,
  purchase_year,
  SUM(line_revenue)
FROM yearly_cohort
GROUP BY
  cohort_year,
  purchase_year
ORDER BY
  cohort_year,
  purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

,cohort_year,purchase_year,sum
0,2015,2015,7370979.48
1,2015,2016,392623.48
2,2015,2017,479841.31
3,2015,2018,1069850.87
4,2015,2019,1235991.48
5,2015,2020,386489.60
6,2015,2021,872845.99
7,2015,2022,1569787.72
8,2015,2023,1157633.91
9,2015,2024,356186.62


In [ ]:
%%sql
--CTE có nghĩa là dùng WITH ... AS ()
WITH yearly_cohort AS (
  SELECT DISTINCT
    EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year,
    customerkey
  FROM sales
)
SELECT
  cohort_year,
  purchase_year,
  COUNT(DISTINCT customerkey) AS num_customers
FROM yearly_cohort
GROUP BY
  cohort_year,
  purchase_year
ORDER BY
  cohort_year,
  purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

,cohort_year,purchase_year,num_customers
0,2015,2015,2825
1,2015,2016,126
2,2015,2017,149
3,2015,2018,348
4,2015,2019,388
5,2015,2020,171
6,2015,2021,295
7,2015,2022,600
8,2015,2023,499
9,2015,2024,146


1. Customer Lifetime Value (LTV) - Giá trị vòng đời khách hàng
* Định nghĩa: Tổng số tiền (doanh thu hoặc lợi nhuận) mà một khách hàng mang lại cho doanh nghiệp trong suốt toàn bộ khoảng thời gian họ gắn bó và sử dụng sản phẩm/dịch vụ của bạn.
* Ý nghĩa: Giúp doanh nghiệp biết được nên chi bao nhiêu tiền để chiêu dụ một khách hàng mới (chi phí marketing/CAC) mà vẫn đảm bảo có lời.
* Ví dụ: Bạn đăng ký gói xem phim Netflix với giá 100.000 VNĐ/tháng và dùng liên tục trong 2 năm (24 tháng) trước khi hủy đăng ký. LTV của bạn đối với Netflix sẽ là:$$100.000 \times 24 = 2.400.000 \text{ VNĐ}$$2. Average Order Value (AOV) - Giá trị đơn hàng trung bình
* Định nghĩa: Số tiền trung bình mà khách hàng chi trả cho một lần mua hàng (một giao dịch).
* Ý nghĩa: Đo lường hành vi mua sắm của khách hàng. Để tăng doanh thu, doanh nghiệp thường tìm cách tăng AOV (ví dụ: gợi ý mua kèm phụ kiện, freeship cho đơn hàng từ x đồng, combo giảm giá).
* Công thức:$$\text{AOV} = \frac{\text{Tổng doanh thu}}{\text{Tổng số lượng đơn hàng}}$$Ví dụ: Trong một ngày, quán trà sữa bán được 3 đơn hàng: Đơn A (50.000đ), Đơn B (150.000đ), Đơn C (100.000đ). Tổng doanh thu là 300.000đ cho 3 đơn. AOV của ngày hôm đó là:$$\frac{300.000}{3} = 100.000 \text{ VNĐ/đơn hàng}$$3. Revenue Per User (Thường gọi là ARPU - Average Revenue Per User) - Doanh thu trung bình trên mỗi người dùngĐịnh nghĩa: Số tiền trung bình mà một người dùng (hoặc một khách hàng kích hoạt) mang lại cho doanh nghiệp trong một khoảng thời gian nhất định (thường tính theo tháng hoặc theo năm).
* Ý nghĩa: Cực kỳ phổ biến trong các ngành như viễn thông, ứng dụng di động (Mobile Apps), game, hoặc các dịch vụ đăng ký định kỳ (SaaS) để đánh giá hiệu quả doanh thu từ tệp người dùng hiện tại.
* Công thức:$$\text{ARPU} = \frac{\text{Tổng doanh thu trong khoảng thời gian } T}{\text{Tổng số người dùng hoạt động trong khoảng thời gian } T}$$Ví dụ: Một ứng dụng học tiếng Anh có 1.000 người dùng hoạt động trong tháng 5. Tổng doanh thu tháng đó từ việc bán tài khoản VIP và quảng cáo là 50.000.000 VNĐ. ARPU của tháng 5 sẽ là:$$\frac{50.000.000}{1.000} = 50.000 \text{ VNĐ/người dùng}$$

In [ ]:
%%sql
WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM (MIN(orderdate))) AS cohort_year,
    SUM(netprice * quantity * exchangerate) AS customer_ltv
  FROM sales
  GROUP BY customerkey
)
SELECT
  *,
  AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_cohort_ltv
FROM yearly_cohort
ORDER BY
  cohort_year,
  customerkey
LIMIT 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

20 rows affected.

,customerkey,cohort_year,customer_ltv,avg_cohort_ltv
0,4376,2015,182.00,5271.59
1,4403,2015,9530.35,5271.59
2,4925,2015,6078.08,5271.59
3,5729,2015,192.16,5271.59
4,6048,2015,1903.89,5271.59
5,6705,2015,13133.76,5271.59
6,9440,2015,208.01,5271.59
7,10806,2015,442.09,5271.59
8,12116,2015,9714.29,5271.59
9,12973,2015,253.06,5271.59


In [ ]:
%%sql
--Dùng WHERE trong window_function,
--filter data before window_function
SELECT
  customerkey,
  EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year
FROM sales
WHERE orderdate >= '2020-01-01'


Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,customerkey,cohort_year
0,15,2021
1,180,2023
2,180,2023
3,387,2021
4,387,2021
...,...,...
124446,2099697,2022
124447,2099697,2022
124448,2099743,2022
124449,2099743,2022


In [ ]:
%%sql
--window_function before filter
WITH cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year
  FROM sales
)
SELECT *
FROM cohort
WHERE cohort_year >= '2020'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

81370 rows affected.

,customerkey,cohort_year
0,15,2021
1,406,2021
2,406,2021
3,545,2023
4,545,2023
...,...,...
81365,2099697,2022
81366,2099697,2022
81367,2099743,2022
81368,2099743,2022


3. RANKING
* ROW_NUMBER() -> 1 2 3 4 5 6 7 8 9
* RANK() ----------> 1 2 3 4 4 4 7 8 8
* DENSE_RANK() --> 1 2 3 4 4 4 5 6 6

In [ ]:
%%sql
WITH row_numbering AS (
  SELECT
    ROW_NUMBER() OVER (
      PARTITION BY orderdate
      ORDER BY
        orderdate,
        orderkey,
        linenumber
    ) AS row_num,
    *
  FROM sales
)
SELECT *
FROM row_numbering
WHERE orderdate > '2015-01-01'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_num,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,2,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,3,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,4,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,5,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,6,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,7,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,8,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,1,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,2,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00


In [ ]:
%%sql
WITH count AS (
  SELECT
    customerkey,
    COUNT(*) AS total_orders
  FROM sales
  GROUP BY
    customerkey
)
SELECT
  *,
  ROW_NUMBER() OVER (ORDER BY total_orders DESC) AS total_orders_row_num,
  RANK() OVER (ORDER BY total_orders DESC) AS total_orders_rank,
  DENSE_RANK() OVER (ORDER BY total_orders DESC) AS total_orders_dense_rank
FROM count
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders,total_orders_row_num,total_orders_rank,total_orders_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6


4. LAG() & LEAD()

In [ ]:
%%sql
WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  FIRST_VALUE(net_revenue) OVER (ORDER BY month) AS first_month_revenue,
  LAST_VALUE(net_revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS first_month_revenue,
  NTH_VALUE(net_revenue, 3) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS third_month_revenue,
  LAG(net_revenue) OVER (ORDER BY month) AS previous_month_revenue,
  LEAD(net_revenue) OVER (ORDER BY month) AS next_month_revenue
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,first_month_revenue,first_month_revenue,third_month_revenue,previous_month_revenue,next_month_revenue
0,2023-01,3664431.34,3664431.34,2928550.93,2244316.52,NaN,4465204.57
1,2023-02,4465204.57,3664431.34,2928550.93,2244316.52,3664431.34,2244316.52
2,2023-03,2244316.52,3664431.34,2928550.93,2244316.52,4465204.57,1162796.16
3,2023-04,1162796.16,3664431.34,2928550.93,2244316.52,2244316.52,2943005.99
4,2023-05,2943005.99,3664431.34,2928550.93,2244316.52,1162796.16,2864500.03
5,2023-06,2864500.03,3664431.34,2928550.93,2244316.52,2943005.99,2337639.34
6,2023-07,2337639.34,3664431.34,2928550.93,2244316.52,2864500.03,2623919.79
7,2023-08,2623919.79,3664431.34,2928550.93,2244316.52,2337639.34,2622774.85
8,2023-09,2622774.85,3664431.34,2928550.93,2244316.52,2623919.79,2551322.61
9,2023-10,2551322.61,3664431.34,2928550.93,2244316.52,2622774.85,2700103.38


In [3]:
%%sql
WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  net_revenue - LAG(net_revenue) OVER (ORDER BY month) AS monthly_revenue_growth
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,monthly_revenue_growth
0,2023-01,3664431.34,NaN
1,2023-02,4465204.57,800773.22
2,2023-03,2244316.52,-2220888.05
3,2023-04,1162796.16,-1081520.36
4,2023-05,2943005.99,1780209.83
5,2023-06,2864500.03,-78505.96
6,2023-07,2337639.34,-526860.69
7,2023-08,2623919.79,286280.45
8,2023-09,2622774.85,-1144.94
9,2023-10,2551322.61,-71452.24


In [ ]:
%%sql
WITH yearly_cohort AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM (MIN(orderdate))) AS cohort_year,
    SUM(netprice * quantity * exchangerate) AS customer_ltv
  FROM sales
  GROUP BY customerkey
)
SELECT
  cohort_year,
  AVG(customer_ltv) AS avg_cohort_ltv,
  100 * (AVG(customer_ltv) - LAG(AVG(customer_ltv)) OVER (ORDER BY cohort_year)) /
  LAG(AVG(customer_ltv)) OVER (ORDER BY cohort_year) AS pre_avg
FROM yearly_cohort
GROUP BY
  cohort_year
ORDER BY
  cohort_year
LIMIT 20

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,cohort_year,avg_cohort_ltv,pre_avg
0,2015,5271.59,NaN
1,2016,5404.92,2.53
2,2017,5403.08,-0.03
3,2018,4896.64,-9.37
4,2019,4731.95,-3.36
5,2020,3933.32,-16.88
6,2021,3943.33,0.25
7,2022,3315.52,-15.92
8,2023,2543.18,-23.29
9,2024,2037.55,-19.88


In [13]:
%%sql
WITH monthly_revenue AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  month,
  net_revenue,
  AVG(net_revenue) OVER (
    ORDER BY month
    ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING
  ), -- từ 1 hàng trước đến 1 hàng sau
  AVG(net_revenue) OVER (
    ORDER BY month
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) -- UNBOUNCED là lấy từ đầu hoặc cuối đến CURRENT
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,avg,avg
0,2023-01,3664431.34,4064817.96,3664431.34
1,2023-02,4465204.57,3457984.14,4064817.96
2,2023-03,2244316.52,2624105.75,3457984.14
3,2023-04,1162796.16,2116706.22,2884187.15
4,2023-05,2943005.99,2323434.06,2895950.92
5,2023-06,2864500.03,2715048.45,2890709.10
6,2023-07,2337639.34,2608686.39,2811699.14
7,2023-08,2623919.79,2528111.33,2788226.72
8,2023-09,2622774.85,2599339.08,2769843.18
9,2023-10,2551322.61,2624733.61,2747991.12
